# 使用 BusyBox 作为基础镜像
# FROM busybox:latest
From ./baseimage
# 设置元数据标签
# LABEL maintainer="your_email@example.com"
# LABEL version="1.0"
# LABEL description="A simple BusyBox example Dockerfile"

# 复制文件到容器中
COPY ./app /usr/src/app

# 设置环境变量
# ENV APP_ENV=production
# ENV APP_PORT=8080

# 暴露端口
# EXPOSE 8080

# 设置入口点
# ENTRYPOINT ["/usr/src/app/my_script.sh"]

# 定义数据卷
# VOLUME ["/usr/src/app/data"]
